### ISSUE TITLE
Sampling strategy

### ISSUE THREAD

**Issue by yaping222** [BlackHC/BatchBALD#2]
Dear Andreas,

Thank you very much for your great code!
I have a question on how you estimate previous joint probability according to sampling.

In your 'sampling.py', you define a function 'sample_M_K'. And you give the following comments:
# probs_N_K_C: #ys x #ws x #classes
# samples_K_M: samples x #ws
# samples = #ws * num_samples_per_w

In my understanding, 'K' means the number of runs with dropout. Could please you give more detailed definitions of 'M' and 'S'?

**Comment by BlackHC** [comment]
A more detailed description of the sampling can be found in the appendix of the arxiv paper: https://arxiv.org/abs/1906.08158

Could you have a look and see if the details there answer you questions?

Thanks,
 Andreas
